/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-04-26 11:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tags/pagination-link.tag", Long.valueOf(1493019538000L));
    _jspx_dependants.put("jar:file:/home/vkarassouloff/training-java/resources/apache-tomcat-8.0.43/webapps/mydeployyy/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/tags/pagination-length.tag", Long.valueOf(1492676080000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492176748000L));
    _jspx_dependants.put("jar:file:/home/vkarassouloff/training-java/resources/apache-tomcat-8.0.43/webapps/mydeployyy/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Computer Database</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"index\"> Application -\n");
      out.write("            Computer Database </a>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("<section id=\"main\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1 id=\"homeTitle\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Computers found</h1>\n");
      out.write("        <div id=\"actions\" class=\"form-horizontal\">\n");
      out.write("            <div class=\"pull-left\">\n");
      out.write("                <form id=\"searchForm\" action=\"#\" method=\"GET\" class=\"form-inline\">\n");
      out.write("                    <input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"search\" id=\"searchbox\" name=\"search\"\n");
      out.write("                           class=\"form-control\" placeholder=\"Search name\"/>\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lengthPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"lengthPage\" />\n");
      out.write("                    <input type=\"submit\" id=\"searchsubmit\" value=\"Filter by name\"\n");
      out.write("                        class=\"btn btn-primary\"/>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"pull-right\">\n");
      out.write("                <a class=\"btn btn-success\" id=\"addComputer\" href=\"computer\">Add Computer</a>\n");
      out.write("                <a class=\"btn btn-default\" id=\"editComputer\" href=\"#\" onclick=\"$.fn.toggleEditMode();\">Edit</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <form id=\"deleteForm\" action=\"#\" method=\"POST\">\n");
      out.write("        <input type=\"hidden\" name=\"selection\" value=\"\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"container\" style=\"margin-top: 10px;\">\n");
      out.write("        <table class=\"table table-striped table-bordered\">\n");
      out.write("            <thead>\n");
      out.write("            <tr>\n");
      out.write("                <!-- Variable declarations for passing labels as parameters -->\n");
      out.write("                <!-- Table header for Computer Name -->\n");
      out.write("\n");
      out.write("                <th class=\"editMode\" style=\"width: 60px; height: 22px;\">\n");
      out.write("                    <input type=\"checkbox\" id=\"selectall\"/>\n");
      out.write("                    <span style=\"vertical-align: top;\"> -\n");
      out.write("                        <a href=\"#\" id=\"deleteSelected\" onclick=\"$.fn.deleteSelected();\">\n");
      out.write("                            <i class=\"fa fa-trash-o fa-lg\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </span>\n");
      out.write("                </th>\n");
      out.write("                <th>Computer name</th>\n");
      out.write("                <th>Introduced date</th>\n");
      out.write("                <!-- Table header for Discontinued Date -->\n");
      out.write("                <th>Discontinued date</th>\n");
      out.write("                <!-- Table header for Company -->\n");
      out.write("                <th>Company</th>\n");
      out.write("            </tr>\n");
      out.write("            </thead>\n");
      out.write("            <!-- Browse attribute computers -->\n");
      out.write("            <tbody id=\"results\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"navbar-fixed-bottom\">\n");
      out.write("    <div class=\"container text-center\">\n");
      out.write("        ");
      if (_jspx_meth_mystuff_005fpagination_002dlink_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_mystuff_005fpagination_002dlength_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"js/dashboard.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/dashboard.jsp(72,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("computer");
      // /WEB-INF/views/dashboard.jsp(72,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dashboard.jsp(72,12) '${computers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${computers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                <tr>\n");
            out.write("                    <td class=\"editMode\"><input type=\"checkbox\" name=\"cb\" class=\"cb\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></td>\n");
            out.write("                    <td><a href=\"computer?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.introduced}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.discontinued}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                </tr>\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mystuff_005fpagination_002dlink_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mystuff:pagination-link
    org.apache.jsp.tag.web.pagination_002dlink_tag _jspx_th_mystuff_005fpagination_002dlink_005f0 = new org.apache.jsp.tag.web.pagination_002dlink_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mystuff_005fpagination_002dlink_005f0);
    try {
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/dashboard.jsp(90,8) name = totalCount type = java.lang.Integer reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setTotalCount((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/dashboard.jsp(90,8) name = itemPerPage type = java.lang.Integer reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setItemPerPage((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lengthPage}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/dashboard.jsp(90,8) name = currentPage type = java.lang.Integer reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setCurrentPage((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/dashboard.jsp(90,8) name = linkGenerated type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setLinkGenerated("index");
      // /WEB-INF/views/dashboard.jsp(90,8) name = paramNameUrlCurrent type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlink_005f0.setParamNameUrlCurrent("currentPage");
      _jspx_th_mystuff_005fpagination_002dlink_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mystuff_005fpagination_002dlink_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mystuff_005fpagination_002dlength_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mystuff:pagination-length
    org.apache.jsp.tag.web.pagination_002dlength_tag _jspx_th_mystuff_005fpagination_002dlength_005f0 = new org.apache.jsp.tag.web.pagination_002dlength_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mystuff_005fpagination_002dlength_005f0);
    try {
      _jspx_th_mystuff_005fpagination_002dlength_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/dashboard.jsp(93,8) name = linkGenerated type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlength_005f0.setLinkGenerated("index");
      // /WEB-INF/views/dashboard.jsp(93,8) name = paramNameLengthList type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlength_005f0.setParamNameLengthList("lengthPage");
      // /WEB-INF/views/dashboard.jsp(93,8) name = displayLength type = java.util.ArrayList<java.lang.Integer> reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_mystuff_005fpagination_002dlength_005f0.setDisplayLength((java.util.ArrayList) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${[20,30,50,100]}", java.util.ArrayList.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_mystuff_005fpagination_002dlength_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mystuff_005fpagination_002dlength_005f0);
    }
    return false;
  }
}
